import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import { getSidebarData } from "./sidebar-data";

export const metadata: Metadata = {
  title: "kylezhao101/content",
  description: "Generated by create next app",
};

export default function DocumentationLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sidebarData = getSidebarData();

  return (
    <div className="flex max-w-screen-2xl mr-auto ml-auto">
      <div className="lg:pl-6">
        <Sidebar sidebarData={sidebarData} />
      </div>
      <div className="pt-14  mb-20 w-full mr-auto ml-auto pl-2 pr-2 sm:pl-6 sm:pr-6">
        {children}
      </div>
    </div>
  );
}
